apiVersion: v1
kind: Pod
metadata:
  name: nodehellowworld.pharosproduction.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000